FROM rabbitmq:3.12-management

COPY rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY rabbitmq/definitions.json /etc/rabbitmq/definitions.json

ENV RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_management load_definitions '/etc/rabbitmq/definitions.json'"

EXPOSE 5672 15672